package profileapp;

/**
* profileapp/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./tasteprofile.idl
* lundi 25 septembre 2017 15 h 11 CEST
*/


/* Type for a User */
public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public profileapp.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (profileapp.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = profileapp.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    profileapp.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return profileapp.UserHelper.type ();
  }

}
