package profileapp;

/**
* profileapp/TopTenHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./tasteprofile.idl
* lundi 25 septembre 2017 15 h 11 CEST
*/


/* Type for top ten users */
public final class TopTenHolder implements org.omg.CORBA.portable.Streamable
{
  public profileapp.TopTen value = null;

  public TopTenHolder ()
  {
  }

  public TopTenHolder (profileapp.TopTen initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = profileapp.TopTenHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    profileapp.TopTenHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return profileapp.TopTenHelper.type ();
  }

}
