package profileapp;
 

/**
* TasteProfile/ProfilerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* lundi 18 septembre 2017 16 h 22 CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
abstract public class ProfilerHelper
{
  private static String  _id = "IDL:TasteProfile/Profiler:1.0";

  public static void insert (org.omg.CORBA.Any a, profileapp.Profiler that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static profileapp.Profiler extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (profileapp.ProfilerHelper.id (), "Profiler");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static profileapp.Profiler read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (ProfilerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, profileapp.Profiler value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static profileapp.Profiler narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof profileapp.Profiler)
      return (profileapp.Profiler)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      profileapp.ProfilerStub stub = new profileapp.ProfilerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static profileapp.Profiler unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof profileapp.Profiler)
      return (profileapp.Profiler)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      profileapp.ProfilerStub stub = new profileapp.ProfilerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
