package profileapp;


/**
* profileapp/Profiler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./tasteprofile.idl
* lundi 25 septembre 2017 15 h 11 CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface Profiler extends ProfilerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Profiler
