package profileapp;


/**
* profileapp/ProfilerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./tasteprofile.idl
* lundi 25 septembre 2017 15 h 11 CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface ProfilerOperations 
{

  /* Returns how many times a given song was played by all the users*/
  int getTimesPlayed (String song_id);

  /* Returns how many times a given song was played by a given user*/
  int getTimesPlayedByUser (String user_id, String song_id);

  /* Returns the profile of the given user */
  profileapp.User getUserProfile (String user_id, String song_id);

  /* Returns the top ten of users */
  profileapp.TopTen getTopTenUsers ();
} // interface ProfilerOperations
