package profileapp;


/**
* profileapp/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./tasteprofile.idl
* lundi 25 septembre 2017 15 h 11 CEST
*/


/* Type for a User */
public abstract class User implements org.omg.CORBA.portable.StreamableValue
{
  public String id = null;
  public profileapp.Song songs[] = null;

  private static String[] _truncatable_ids = {
    profileapp.UserHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.id = istream.read_string ();
    int _len0 = istream.read_long ();
    this.songs = new profileapp.Song[_len0];
    for (int _o1 = 0;_o1 < this.songs.length; ++_o1)
      this.songs[_o1] = profileapp.SongHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_string (this.id);
    ostream.write_long (this.songs.length);
    for (int _i0 = 0;_i0 < this.songs.length; ++_i0)
      profileapp.SongHelper.write (ostream, this.songs[_i0]);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return profileapp.UserHelper.type ();
  }
} // class User
